-- SPDX-FileCopyrightText: 2026 m00nyONE STUDLETON BobDRAD
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomNames"
local lib = _G[lib_name]
local n = lib.GetNamesTable()

-- this list is maintained by @BobDRAD on PS-NA. Codes generated by https://eso-names.bobdrad.com

n["@AnchorLady118"] = {"AnchorLady", "|c5e00ffA|r|c6f00ffn|r|c8100ffc|r|c9300ffh|r|ca500ffo|r|cb700ffr|r|cc900ffL|r|cdb00ffa|r|ced00ffd|r|cff00ffy|r"}
n["@Angels_Slaughter"] = {"Angel (*.*)", "|cBD0404A|r|cC3042An|r|cCA0353g|r|cD1037Ee|r|cD703ADl|r|cDE02DE |r|cB702E4(|r|c8E01EB*|r|c6101F2.|r|c3200F8*|r|c0000FF)|r"}
n["@BakerBakker"] = {"Baker", "|c0cf3dbB|r|c0cf3dba|r|c0cf3dbk|r|c0cf3dbe|r|c0cf3dbr|r"}
n["@BobDRAD"] = {"Dread Bob", "|cFF0000D|r|cFC1B00r|r|cFA3600e|r|cF75000a|r|cF56A00d|r|cF28300 |r|cF09C00B|r|cEDB400o|r|cEBCB00b|r"}
n["@cheezhead84"] = {"Cheez", "|c1c8c07C|r|c4d9f06h|r|c7fb306e|r|cb0c606e|r|ce2da06z|r"}
n["@famed_taxpayer1"] = {"Famed <3", "|cff00fbF|r|cda21fba|r|cb643fcm|r|c9165fce|r|c6d86fdd|r|c48a8fd |r|c24cafe<|r|c00ecff3|r"}
n["@ImmolationO_o"] = {"Immolation xD", "|cf10000I|r|cf21300m|r|cf32600m|r|cf43900o|r|cf54d01l|r|cf66001a|r|cf87301t|r|cf98601i|r|cfa9a02o|r|cfbad02n|r|cfcc002 |r|cfdd302x|r|cffe703D|r"}
n["@ll_NooGz_ll"] = {"ll_NooGz_ll", "|cf36b31l|r|cf46045l|r|cf5555a_|r|cf64a6eN|r|cf74083o|r|cf93598o|r|cfa2aacG|r|cfb20c1z|r|cfc15d5_|r|cfd0aeal|r|cff00ffl|r"}
n["@madridgirl7"] = {"madridgirl7", "|cfff600m|r|cfcdd19a|r|cf9c433d|r|cf6ac4cr|r|cf49366i|r|cf17b7fd|r|cee6299g|r|cec49b2i|r|ce931ccr|r|ce618e5l|r|ce400ff7|r"}
n["@Mikes-Swagger00"] = {"Swagger-.-", "|c3ebd34S|r|c50b63aw|r|c63af40a|r|c75a846g|r|c88a14cg|r|c9a9b52e|r|cad9458r|r|cbf8d5e-|r|cd28664.|r|ce5806b-|r"}
n["@occult_biscuit11"] = {"Biscuit", "|c9561E8B|r|cA564E7i|r|cB567E6s|r|cC36AE6c|r|cD16CE5u|r|cDE6FE4i|r|cE371DBt|r"}
n["@piefase"] = {"Pie", "|cea07c2P|r|cea07cai|r|cea07d3e|r"}
n["@Robotom-9000"] = {"Robotom-9000", "|c00c9feR|r|c16cde6o|r|c2cd2cfb|r|c43d7b8o|r|c59dca1t|r|c6fe18ao|r|c86e673m|r|c9ceb5c-|r|cb2f0459|r|cc9f52e0|r|cdffa170|r|cf6ff000|r"}
n["@RocklicenseDTB"] = {"Rock -_-", "|cffe335R|r|cffe52do|r|cffe725c|r|cffea1ek|r|cffec16 |r|cffef0f-|r|cfff107_|r|cfff400-|r"}
n["@WrathOfKore"] = {"~Wrath~", "|cba08f3~|r|cc50bcbW|r|cd00ea4r|r|cdb117da|r|ce61456t|r|cf1172fh|r|cfd1b08~|r"}
n["@xSherman___"] = {"Sherman", "|c000000S|r|c000000h|r|c000000e|r|c000000r|r|c000000m|r|c000000a|r|c000000n|r"}
n["@xYouknowthevibes"] = {"Vibes", "|cff0000V|r|cbf003fi|r|c7f007fb|r|c3f00bfe|r|c0000ffs|r"}